-- ==============================================================================
-- V9__seed_all_departments_books.sql
-- Ensure comprehensive demo inventory across all 10 departments and engineering disciplines,
-- specifically providing textbook titles for Engineering Physics & Chemistry, Applied Math, etc.
-- ==============================================================================

INSERT INTO books (
    id, isbn, title, subtitle, author_id, author_name, category_id, category_name,
    publisher, publication_year, edition, language, description, cover_image,
    total_copies, available_copies, location, shelf_number, book_type, digital_available,
    digital_file, status
) VALUES
(42, '978-0470568378', 'Engineering Physics: Principles and Optics', 'Electromagnetism, Quantum Mechanics, and Fiber Optics', 12, 'Erwin Kreyszig', 8, 'Engineering Physics & Chemistry', 'Wiley', 2021, '5th Edition', 'English', 'Comprehensive physics text covering wave optics, laser systems, superconductivity, and quantum physics applications in modern engineering.', 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=500&q=80', 10, 8, 'Basic Sciences Wing', 'BSCI-A-101', 'BOTH', TRUE, '/api/v1/resources/download/sample-physics.pdf', 'AVAILABLE'),
(43, '978-8174092440', 'Engineering Chemistry and Material Analysis', 'Water Technology, Polymer Chemistry, and Nano-materials', 8, 'Ian Sommerville', 8, 'Engineering Physics & Chemistry', 'Dhanpat Rai', 2022, '16th Edition', 'English', 'Foundational chemistry reference for technical colleges covering thermodynamics, electrochemistry, corrosion control, and green engineering.', 'https://images.unsplash.com/photo-1532094349884-543bc11b234d?w=500&q=80', 12, 10, 'Basic Sciences Wing', 'BSCI-B-108', 'BOTH', TRUE, '/api/v1/resources/download/sample-chemistry.pdf', 'AVAILABLE'),
(44, '978-1119454151', 'Materials Science and Metallurgy for Engineers', 'Atomic Bonding, Crystal Structures, and Mechanical Testing', 5, 'Abraham Silberschatz', 8, 'Engineering Physics & Chemistry', 'Wiley', 2020, '10th Edition', 'English', 'Standard introductory text exploring the relationship between the structural elements of materials and their properties in engineering design.', 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=500&q=80', 8, 6, 'Basic Sciences Wing', 'BSCI-C-115', 'PHYSICAL', FALSE, NULL, 'AVAILABLE'),
(45, '978-0073383095', 'Discrete Mathematics and Its Applications', 'Graph Theory, Combinatorics, and Boolean Algebra', 1, 'Thomas H. Cormen', 7, 'Applied Mathematics', 'McGraw-Hill', 2021, '8th Edition', 'English', 'The world-renowned discrete math curriculum for computing and electrical sciences, detailing set theory, proof methods, and recursion.', 'https://images.unsplash.com/photo-1509228468518-180dd4864904?w=500&q=80', 14, 11, 'Basic Sciences Wing', 'MATH-C-310', 'BOTH', TRUE, '/api/v1/resources/download/sample-discrete-math.pdf', 'AVAILABLE'),
(46, '978-8174091955', 'Higher Engineering Mathematics', 'Vector Calculus, Series Solutions, and Numerical Techniques', 12, 'Erwin Kreyszig', 7, 'Applied Mathematics', 'Khanna Publishers', 2022, '44th Edition', 'English', 'Essential college mathematics text covering transforms, partial differential equations, probability distributions, and boundary value problems.', 'https://images.unsplash.com/photo-1635070041078-e363dbe005cb?w=500&q=80', 15, 12, 'Basic Sciences Wing', 'MATH-D-315', 'BOTH', TRUE, '/api/v1/resources/download/sample-higher-math.pdf', 'AVAILABLE'),
(47, '978-0133125900', 'Power Electronics: Devices, Circuits, and Applications', 'Semiconductor Switches, Converters, and Inverter Systems', 4, 'Andrew S. Tanenbaum', 4, 'Electronics & Communication', 'Pearson', 2022, '4th Edition', 'English', 'Comprehensive survey of power diodes, thyristors, MOSFETs, IGBT gate drives, DC-DC buck-boost converters, and resonant inverters.', 'https://images.unsplash.com/photo-1518770660439-4636190af475?w=500&q=80', 8, 6, 'Electronics Block', 'ECE-C-212', 'BOTH', TRUE, '/api/v1/resources/download/sample-power-electronics.pdf', 'AVAILABLE'),
(48, '978-0199460915', 'Design of Steel Structures', 'Limit State Method, Connections, and Structural Elements', 12, 'Erwin Kreyszig', 6, 'Civil Engineering', 'Oxford University Press', 2020, '2nd Edition', 'English', 'Practical engineering guide adhering to standard building codes, detailing tension members, compression columns, and roof trusses.', 'https://images.unsplash.com/photo-1541888946425-d0fbb186c5f7?w=500&q=80', 7, 5, 'Civil Dept Wing', 'CE-D-114', 'PHYSICAL', FALSE, NULL, 'AVAILABLE'),
(49, '978-9353163198', 'Manufacturing Technology: Metal Cutting and Machine Tools', 'Machining Processes, CNC Programming, and Tool Wear', 10, 'Herbert Schildt', 5, 'Mechanical Engineering', 'McGraw-Hill', 2021, '4th Edition', 'English', 'Covers cutting tool geometry, lathe operations, milling machines, grinding technology, and computer-integrated manufacturing fundamentals.', 'https://images.unsplash.com/photo-1581092160607-ee22621dd758?w=500&q=80', 9, 7, 'Mechanical Dept Wing', 'ME-D-220', 'BOTH', TRUE, '/api/v1/resources/download/sample-manufacturing.pdf', 'AVAILABLE');

ALTER TABLE books ALTER COLUMN id RESTART WITH 150;
