-- ==============================================================================
-- SUPABASE POSTGRESQL SETUP SCRIPT
-- Digital Library Management System
-- Institution: Thakur Shree DPS College of Engineering and Management
-- Project Team: Ashish Yadav, Rahul Yadav, Priyanshu Yadav
--
-- Instructions:
-- 1. Open your Supabase project dashboard: https://supabase.com/dashboard
-- 2. Navigate to "SQL Editor" -> "New query"
-- 3. Paste this entire script and click "Run"
-- 4. In Render or .env, configure:
--    DATABASE_URL=jdbc:postgresql://db.<PROJECT-REF>.supabase.co:5432/postgres?sslmode=require
--    DATABASE_USERNAME=postgres
--    DATABASE_PASSWORD=<YOUR-SUPABASE-DB-PASSWORD>
-- ==============================================================================

-- Supabase SQL Editor does not support psql's \i include command.
-- Run database/schema.sql first, then database/seed_data.sql in two SQL Editor
-- queries. For a deployed backend, prefer the Flyway migrations instead:
-- set SPRING_PROFILES_ACTIVE=postgres and configure the datasource variables.

